export interface Component {
  label: string;
  value: string;
  dependencies: string[];
  internal_dependencies: string[];
}

export const allComponents: Component[] = [
  {
    label: "Accordion",
    value: "accordion",
    dependencies: ["@radix-ui/react-accordion"],
    internal_dependencies: [],
  },
  {
    label: "Alert",
    value: "alert",
    dependencies: ["class-variance-authority"],
    internal_dependencies: [],
  },
  {
    label: "Alert Dialog",
    value: "alert-dialog",
    dependencies: ["@radix-ui/react-alert-dialog"],
    internal_dependencies: [],
  },
  {
    label: "Aspect Ratio",
    value: "aspect-ratio",
    dependencies: ["@radix-ui/react-aspect-ratio"],
    internal_dependencies: [],
  },
  {
    label: "Avatar",
    value: "avatar",
    dependencies: ["@radix-ui/react-avatar"],
    internal_dependencies: [],
  },
  {
    label: "Badge",
    value: "badge",
    dependencies: ["class-variance-authority"],
    internal_dependencies: [],
  },
  {
    label: "Breadcrumb",
    value: "breadcrumb",
    dependencies: ["@radix-ui/react-slot"],
    internal_dependencies: [],
  },
  {
    label: "Button",
    value: "button",
    dependencies: ["@radix-ui/react-slot", "class-variance-authority"],
    internal_dependencies: [],
  },
  {
    label: "Calendar",
    value: "calendar",
    dependencies: ["react-day-picker"],
    internal_dependencies: ["button"],
  },
  {
    label: "Card",
    value: "card",
    dependencies: [],
    internal_dependencies: [],
  },
  {
    label: "Carousel",
    value: "carousel",
    dependencies: ["embla-carousel-react"],
    internal_dependencies: ["button"],
  },
  {
    label: "Chart",
    value: "chart",
    dependencies: ["recharts"],
    internal_dependencies: [],
  },
  {
    label: "Checkbox",
    value: "checkbox",
    dependencies: ["@radix-ui/react-checkbox"],
    internal_dependencies: [],
  },
  {
    label: "Collapsible",
    value: "collapsible",
    dependencies: ["@radix-ui/react-collapsible"],
    internal_dependencies: [],
  },
  {
    label: "Command",
    value: "command",
    dependencies: ["cmdk"],
    internal_dependencies: ["dialog"],
  },
  {
    label: "Context Menu",
    value: "context-menu",
    dependencies: ["@radix-ui/react-context-menu"],
    internal_dependencies: [],
  },
  {
    label: "Dialog",
    value: "dialog",
    dependencies: ["@radix-ui/react-dialog"],
    internal_dependencies: [],
  },
  {
    label: "Drawer",
    value: "drawer",
    dependencies: ["vaul"],
    internal_dependencies: [],
  },
  {
    label: "Dropdown Menu",
    value: "dropdown-menu",
    dependencies: ["@radix-ui/react-dropdown-menu"],
    internal_dependencies: [],
  },
  {
    label: "React Hook Form",
    value: "form",
    dependencies: ["react-hook-form", "@hookform/resolvers"],
    internal_dependencies: ["label"],
  },
  {
    label: "Hover Card",
    value: "hover-card",
    dependencies: ["@radix-ui/react-hover-card"],
    internal_dependencies: [],
  },
  {
    label: "Input",
    value: "input",
    dependencies: [],
    internal_dependencies: [],
  },
  {
    label: "Input OTP",
    value: "input-otp",
    dependencies: ["input-otp"],
    internal_dependencies: [],
  },
  {
    label: "Label",
    value: "label",
    dependencies: ["@radix-ui/react-label"],
    internal_dependencies: [],
  },
  {
    label: "Menubar",
    value: "menubar",
    dependencies: ["@radix-ui/react-menubar"],
    internal_dependencies: [],
  },
  {
    label: "Navigation Menu",
    value: "navigation-menu",
    dependencies: [
      "@radix-ui/react-navigation-menu",
      "class-variance-authority",
    ],
    internal_dependencies: [],
  },
  {
    label: "Pagination",
    value: "pagination",
    dependencies: [],
    internal_dependencies: ["button"],
  },
  {
    label: "Popover",
    value: "popover",
    dependencies: ["@radix-ui/react-popover"],
    internal_dependencies: [],
  },
  {
    label: "Progress",
    value: "progress",
    dependencies: ["@radix-ui/react-progress"],
    internal_dependencies: [],
  },
  {
    label: "Radio Group",
    value: "radio-group",
    dependencies: ["@radix-ui/react-radio-group"],
    internal_dependencies: [],
  },
  {
    label: "Resizable",
    value: "resizable",
    dependencies: ["react-resizable-panels"],
    internal_dependencies: [],
  },
  {
    label: "Scroll-area",
    value: "scroll-area",
    dependencies: ["@radix-ui/react-scroll-area"],
    internal_dependencies: [],
  },
  {
    label: "Select",
    value: "select",
    dependencies: ["@radix-ui/react-select"],
    internal_dependencies: [],
  },
  {
    label: "Separator",
    value: "separator",
    dependencies: ["@radix-ui/react-separator"],
    internal_dependencies: [],
  },
  {
    label: "Sheet",
    value: "sheet",
    dependencies: ["@radix-ui/react-dialog"],
    internal_dependencies: [],
  },
  {
    label: "Sidebar",
    value: "sidebar",
    dependencies: ["@radix-ui/react-slot", "class-variance-authority"],
    internal_dependencies: [
      "button",
      "input",
      "separator",
      "sheet",
      "skeleton",
      "tooltip",
    ],
  },
  {
    label: "Skeleton",
    value: "skeleton",
    dependencies: [],
    internal_dependencies: [],
  },
  {
    label: "Slider",
    value: "slider",
    dependencies: ["@radix-ui/react-slider"],
    internal_dependencies: [],
  },
  {
    label: "Sonner",
    value: "sonner",
    dependencies: ["sonner"],
    internal_dependencies: [],
  },
  {
    label: "Switch",
    value: "switch",
    dependencies: ["@radix-ui/react-switch"],
    internal_dependencies: [],
  },
  {
    label: "Table",
    value: "table",
    dependencies: [],
    internal_dependencies: [],
  },
  {
    label: "Tabs",
    value: "tabs",
    dependencies: ["@radix-ui/react-tabs"],
    internal_dependencies: [],
  },
  {
    label: "Textarea",
    value: "textarea",
    dependencies: [],
    internal_dependencies: [],
  },
  {
    label: "Toggle",
    value: "toggle",
    dependencies: ["@radix-ui/react-toggle", "class-variance-authority"],
    internal_dependencies: [],
  },
  {
    label: "Toggle Group",
    value: "toggle-group",
    dependencies: ["@radix-ui/react-toggle-group", "class-variance-authority"],
    internal_dependencies: ["toggle"],
  },
  {
    label: "Tooltip",
    value: "tooltip",
    dependencies: ["@radix-ui/react-tooltip"],
    internal_dependencies: [],
  },
];
